# בחר בתמונת בסיס של Node.js
FROM node:14

# הגדר את התיקייה העבור היישום
WORKDIR /app

# העתק את קובץ ה package.json והפקודות שורת הפקודה
COPY package*.json ./

# התקן את התלתת
RUN npm install

# העתק את שאר קבצי היישום
COPY . .

# הגדר את הפורט שבו השרת יפנה
EXPOSE 3000

# התחל את השרת
CMD ["node", "server.js"]
